#+TYP_TODO: MAYBE DONE TODO

* rewrite process->script
The =process->script= procedure in =(gwl processes)= is the absolute worst.  It is hard to understand, overly long, terribly nested.  It needs a careful rewrite and excellent tests.

* documentation
- document the cache
- add a procedure reference

* containerization
- mount the GWL cache directories for inputs and outputs (not the full cache)

* catch Ctrl-C and abort execution of all processes, not just the current one

* web interface needs C-c twice to terminate
This is a common problem with Guile web server applications.  For some reason installing a SIGINT signal handler (as the web server does) causes the first =C-c= to be swallowed.

* --output option has no effect!
This should serve as a prefix for all output files.  But how would this affect processes that use output files as inputs?

* add gettext support for all output

* add verbosity control
All the GWL output (such as “Executing” or “Skipping”) should respond to verbosity settings.

* add support for guile-ssh to submit jobs via SSH
or can we just use “guix deploy” directly?

* add support for external execution engines?  (DRMAA, AWS, Azure)
- write [[https://git.elephly.net/?p=software/guile-aws.git;a=summary][guile-aws library]]

* GWL cache

** [kyle] Make data caching git-annex aware
 When deciding to recompute data files, GWL avoids computing the hash
 of data files, using scripts as the cheaper proxy, as you described in
 87womnnjg0.fsf@elephly.net.  But if the user is tracking data files
 with git-annex, getting the hash of data files becomes less expensive
 because we can ask git-annex for the hash it has already computed.

** Get annex data files on demand if needed as inputs
i.e. fetch them with =git annex get=

** Make cache IPFS aware
This is similar to the git-annex work

* MAYBE change =run-time= field
it only accepts a “complexity” value, so remove that and assume that all arguments do in fact constitute a complexity.  It would turn this:

#+BEGIN_SRC wisp
process foo
  run-time
    complexity
      space 20 MiB
      time 10 seconds
#+END_SRC

…to this:

#+BEGIN_SRC wisp
process foo
  resources
    space 20 MiB
    time 10 seconds
#+END_SRC

Or rather: let the “resources” field accept an arbitrary list of resource values.

* Documentation
Only the HTML files have highlighting, not the gzipped  HTML files!
